[project]
name = "nhm-spider"
version = "3.4.3"
description = "base on asyncio, spider module like scrapy."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "noHairMan", email = "zongxuheng@163.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp>=3.13.3",
    "aiohttp-socks>=0.11.0",
    "parsel>=1.11.0",
    "playwright>=1.58.0",
]


[dependency-groups]
dev = [
    "build>=1.4.0",
    "pre-commit>=4.5.1",
    "pytest-asyncio>=1.3.0",
    "twine>=6.2.0",
]


[project.urls]
"Homepage" = "https://github.com/noHairMan/nhm-spider"

[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]

[[tool.uv.index]]
url = "https://pypi.python.org/simple/"
default = true

[tool.black]
line_length = 120

[tool.isort]
profile = "black"
src_paths = ["src"]
py_version = 314
skip_gitignore = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["nhm_spider"]
multi_line_output = 3
line_length = 120
